#!/usr/bin/env python
# -*- coding: utf-8 -*-"
# vim: set expandtab tabstop=4 shiftwidth=4:
"""
This file is part of the XSSer project, https://xsser.03c8.net

Copyright (c) 2010/2026 | psy <epsylon@riseup.net>

xsser is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free
Software Foundation version 3 of the License.

xsser is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
details.

You should have received a copy of the GNU General Public License along
with xsser; if not, write to the Free Software Foundation, Inc., 51
Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
"""
import os, datetime

DARK = (30, 33, 41)
ACCENT = (198, 40, 40)
GREEN = (33, 115, 70)
GREY = (110, 118, 129)
LIGHT = (244, 245, 247)
WHITE = (255, 255, 255)
GOLD = (240, 182, 42)

def _logo_path():
    here = os.path.dirname(os.path.abspath(__file__))
    for cand in (os.path.join(here, "..", "..", "gtk", "images", "xsser.jpg"),
                 "gtk/images/xsser.jpg"):
        if os.path.exists(cand):
            return cand
    return None

def _load_fpdf():
    try:
        from fpdf import FPDF
        return FPDF
    except ImportError:
        try:
            from core._ensure import ensure
        except ImportError:
            return None
        if ensure('fpdf', 'fpdf2') is None:
            return None
        try:
            from fpdf import FPDF
            return FPDF
        except ImportError:
            return None

def _s(text):
    return str(text).encode('latin-1', 'replace').decode('latin-1')

class pdf_reporting(object):
    """
    Print results from an attack as a professional PDF report.
    """
    def __init__(self, xsser):
        self.instance = xsser

    def _build_pdf_class(self, FPDF):
        class _PDF(FPDF):
            def header(self):
                self.set_fill_color(*DARK)
                self.rect(0, 0, self.w, 24, 'F')
                self.set_fill_color(*GOLD)
                self.rect(0, 24, self.w, 1.3, 'F')
                logo = _logo_path()
                if logo:
                    self.set_fill_color(*WHITE)
                    self.rect(10, 4.5, 15, 15, 'F')
                    try:
                        self.image(logo, 11.3, 5.6, 12.4, 12.4)
                    except Exception:
                        pass
                    tx = 30
                else:
                    tx = 10
                self.set_text_color(*WHITE)
                self.set_xy(tx, 5)
                self.set_font('Helvetica', 'B', 15)
                self.cell(0, 8, 'XSSer v1.9  "Bl4ck Swarm!"', 0, 1, 'L')
                self.set_x(tx)
                self.set_font('Helvetica', '', 8)
                self.set_text_color(190, 190, 195)
                self.cell(0, 5, 'Cross Site Scripting - Security Assessment Report', 0, 0, 'L')
                self.cell(0, 5, 'https://xsser.03c8.net', 0, 1, 'R')
                self.set_y(31)
                self.set_text_color(*DARK)
            def footer(self):
                self.set_y(-13)
                self.set_draw_color(*GREY)
                self.set_line_width(0.2)
                self.line(10, self.get_y(), self.w - 10, self.get_y())
                self.set_y(-11)
                self.set_font('Helvetica', 'I', 7)
                self.set_text_color(*GREY)
                self.cell(0, 6, 'Generated by XSSer v1.9 - for authorized security testing only', 0, 0, 'L')
                self.cell(0, 6, 'Page ' + str(self.page_no()) + '/{nb}', 0, 0, 'R')
        return _PDF

    def _section(self, pdf, title, color=DARK):
        pdf.ln(3)
        pdf.set_fill_color(*color)
        pdf.set_text_color(*WHITE)
        pdf.set_font('Helvetica', 'B', 11)
        pdf.cell(0, 8, '  ' + _s(title), 0, 1, 'L', True)
        pdf.set_text_color(*DARK)
        pdf.ln(2)

    def _kv(self, pdf, key, value, kcolor=DARK):
        pdf.set_x(pdf.l_margin)
        pdf.set_font('Helvetica', 'B', 9)
        pdf.set_text_color(*kcolor)
        pdf.cell(38, 6, _s(key), 0, 0, 'L')
        pdf.set_font('Helvetica', '', 9)
        pdf.set_text_color(*DARK)
        w = pdf.w - pdf.r_margin - pdf.get_x()
        pdf.multi_cell(w, 6, _s(value) or "-")
        pdf.set_x(pdf.l_margin)

    def _payload_block(self, pdf, payload):
        pdf.set_x(pdf.l_margin)
        pdf.set_font('Courier', 'B', 8)
        pdf.set_fill_color(*LIGHT)
        pdf.set_text_color(20, 20, 20)
        w = pdf.w - pdf.l_margin - pdf.r_margin
        pdf.multi_cell(w, 5, _s(payload) or "-", 0, 'L', True)
        pdf.set_text_color(*DARK)

    def print_pdf_results(self, filename):
        FPDF = _load_fpdf()
        if FPDF is None:
            print("\n[Error] Missing lib: 'fpdf2'. Install it with: pip3 install fpdf2\n")
            return
        inst = self.instance
        found = list(getattr(inst, 'hash_found', []))
        notfound = list(getattr(inst, 'hash_notfound', []))
        total = len(found) + len(notfound)
        try:
            accur = str(round(len(found) * 100.0 / total, 1)) + " %"
        except ZeroDivisionError:
            accur = "0 %"
        pdf = self._build_pdf_class(FPDF)()
        pdf.alias_nb_pages()
        pdf.set_auto_page_break(True, 16)
        pdf.add_page()

        opts = inst.options
        target = opts.url or opts.target or opts.dork or opts.readfile or "multiple target(s)"
        pdf.set_font('Helvetica', '', 10)
        self._kv(pdf, "Date:", str(datetime.datetime.now()).split('.')[0])
        self._kv(pdf, "Target:", target)
        try:
            vectors_loaded = str(inst.optionParser.total_vectors)
        except Exception:
            vectors_loaded = "-"
        self._kv(pdf, "Vectors loaded:", vectors_loaded)

        self._section(pdf, "EXECUTIVE SUMMARY")
        self._kv(pdf, "Injections:", str(total) + " total   |   " + str(len(found)) + " successful   |   " + str(len(notfound)) + " filtered/failed")
        self._kv(pdf, "Accuracy:", accur)
        try:
            total_con = inst.success_connection + inst.not_connection + inst.forwarded_connection + inst.other_connection
            self._kv(pdf, "Connections:", str(total_con) + " total   |   " + str(inst.success_connection) + " ok   |   " + str(inst.not_connection) + " failed")
        except Exception:
            pass
        if getattr(opts, 'statistics', False):
            try:
                self._kv(pdf, "Duration:", str(datetime.datetime.now() - inst.time).split('.')[0])
            except Exception:
                pass

        techniques = inst.get_techniques_used() if hasattr(inst, 'get_techniques_used') else []
        command = inst.get_command_used() if hasattr(inst, 'get_command_used') else ""
        if command or techniques:
            self._section(pdf, "COMMAND & TECHNIQUES")
            if command:
                pdf.set_font('Helvetica', 'B', 9)
                pdf.set_text_color(*DARK)
                pdf.cell(38, 6, "Command:", 0, 1, 'L')
                pdf.set_x(pdf.l_margin)
                pdf.set_font('Courier', 'B', 8)
                pdf.set_fill_color(*DARK)
                pdf.set_text_color(*GOLD)
                w = pdf.w - pdf.l_margin - pdf.r_margin
                pdf.multi_cell(w, 5, _s(command) or "-", 0, 'L', True)
                pdf.set_text_color(*DARK)
                pdf.ln(2)
            if techniques:
                self._kv(pdf, "Techniques:", ", ".join(techniques))

        if found:
            self._section(pdf, "VULNERABILITIES FOUND (" + str(len(found)) + ")", ACCENT)
            n = 0
            for line in found:
                n += 1
                if len(line) > 1 and line[1] == "[Heuristic test]":
                    pdf.set_font('Helvetica', 'B', 10)
                    pdf.set_text_color(*ACCENT)
                    pdf.cell(0, 6, _s("[+] Finding #" + str(n) + " - Heuristic (character NOT FILTERED)"), 0, 1, 'L')
                    pdf.set_text_color(*DARK)
                    self._kv(pdf, "Target:", str(line[6]) if len(line) > 6 else str(target))
                    self._kv(pdf, "Character:", str(line[5]) if len(line) > 5 else "")
                    self._kv(pdf, "Status:", "NOT FILTERED (passes through to the target)")
                    pdf.ln(2)
                    continue
                if len(line) > 1 and line[1] == "[hashing check]":
                    pdf.set_font('Helvetica', 'B', 10)
                    pdf.set_text_color(*ACCENT)
                    pdf.cell(0, 6, _s("[+] Finding #" + str(n) + " - Hashing check (reflected)"), 0, 1, 'L')
                    pdf.set_text_color(*DARK)
                    self._kv(pdf, "Target:", str(line[6]) if len(line) > 6 else str(target))
                    self._kv(pdf, "Status:", "HASH FOUND (parameter reflects input)")
                    pdf.ln(2)
                    continue
                method = str(line[2]).upper() if len(line) > 2 else "URL"
                tgt = str(line[6]) if len(line) > 6 else str(target)
                pdf.set_font('Helvetica', 'B', 10)
                pdf.set_text_color(*ACCENT)
                pdf.cell(0, 6, _s("[+] Finding #" + str(n) + " - " + method + " Cross Site Scripting"), 0, 1, 'L')
                pdf.set_text_color(*DARK)
                self._kv(pdf, "Target:", tgt)
                if len(line) > 1 and line[1]:
                    self._kv(pdf, "Context:", str(line[1]))
                pdf.set_font('Helvetica', 'B', 9)
                pdf.cell(38, 6, "Payload:", 0, 1, 'L')
                self._payload_block(pdf, line[0])
                pdf.ln(3)
        else:
            self._section(pdf, "VULNERABILITIES FOUND (0)", GREEN)
            pdf.set_font('Helvetica', '', 10)
            pdf.multi_cell(0, 6, "No XSS injections were confirmed on the audited target(s) with the vectors used.")

        if notfound:
            self._section(pdf, "FILTERED / FAILED INJECTIONS (" + str(len(notfound)) + ")")
            pdf.set_font('Helvetica', '', 9)
            pdf.multi_cell(0, 6, _s(str(len(notfound)) + " injection(s) were sent but not reflected back unfiltered (target may filter/encode these vectors)."))

        pdf.output(filename)
